version: "3.7"
services:

  app:
    build:
      args:
        user: joaotavioos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: education
    container_name: questions-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - education
    ports:
     - 3000:3000

  db:
    image: mysql:5.7
    container_name: questions-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - education

  nginx:
    image: nginx:alpine
    container_name: education-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - education

  mysql-ui:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - education

networks:
  education:
    driver: bridge